-- This script attempts to create a pivot table in bookBook_main_db
-- pivots book to rows and users to columns with ratings at intersection

SELECT ISBN,
       sum(IF(ID=1, Rating, NULL)) AS '1',
       sum(IF(ID=2, Rating, NULL)) AS '2',
       sum(IF(ID=3, Rating, NULL)) AS '3',
       sum(IF(ID=4, Rating, NULL)) AS '4',
       sum(IF(ID=5, Rating, NULL)) AS '5',
       sum(IF(ID=6, Rating, NULL)) AS '6',
       sum(IF(ID=7, Rating, NULL)) AS '7',
       sum(IF(ID=8, Rating, NULL)) AS '8',
       sum(IF(ID=9, Rating, NULL)) AS '9',
       sum(IF(ID=10, Rating, NULL)) AS '10',
       sum(IF(ID=11, Rating, NULL)) AS '11',
       sum(IF(ID=12, Rating, NULL)) AS '12',
       sum(IF(ID=13, Rating, NULL)) AS '13',
       sum(IF(ID=14, Rating, NULL)) AS '14',
       sum(IF(ID=15, Rating, NULL)) AS '15',
       sum(IF(ID=16, Rating, NULL)) AS '16',
       sum(IF(ID=17, Rating, NULL)) AS '17',
       sum(IF(ID=18, Rating, NULL)) AS '18',
       sum(IF(ID=19, Rating, NULL)) AS '19',
       sum(IF(ID=20, Rating, NULL)) AS '20',
       sum(IF(ID=21, Rating, NULL)) AS '21',
       sum(IF(ID=22, Rating, NULL)) AS '22',
       sum(IF(ID=23, Rating, NULL)) AS '23',
       sum(IF(ID=24, Rating, NULL)) AS '24',
       sum(IF(ID=25, Rating, NULL)) AS '25',
       sum(IF(ID=26, Rating, NULL)) AS '26',
       sum(IF(ID=27, Rating, NULL)) AS '27',
       sum(IF(ID=28, Rating, NULL)) AS '28',
       sum(IF(ID=29, Rating, NULL)) AS '29',
       sum(IF(ID=30, Rating, NULL)) AS '30'
FROM BookRatings
GROUP BY ISBN;
