-- This script attempts to create a pivot table in bookBook_main_db
-- pivots book to rows and users to columns with ratings at intersection

SELECT B.`ISBN`,
       sum(IF(B.`ID`=1, B.`Rating`, NULL)) AS 1,
       sum(IF(B.`ID`=2, B.`Rating`, NULL)) AS 2,
       sum(IF(B.`ID`=3, B.`Rating`, NULL)) AS 3,
       sum(IF(B.`ID`=4, B.`Rating`, NULL)) AS 4,
       sum(IF(B.`ID`=5, B.`Rating`, NULL)) AS 5,
       sum(IF(B.`ID`=6, B.`Rating`, NULL)) AS 6,
       sum(IF(B.`ID`=7, B.`Rating`, NULL)) AS 7,
       sum(IF(B.`ID`=8, B.`Rating`, NULL)) AS 8,
       sum(IF(B.`ID`=9, B.`Rating`, NULL)) AS 9,
       sum(IF(B.`ID`=10, B.`Rating`, NULL)) AS 10,
       sum(IF(B.`ID`=11, B.`Rating`, NULL)) AS 11,
       sum(IF(B.`ID`=12, B.`Rating`, NULL)) AS 12,
       sum(IF(B.`ID`=13, B.`Rating`, NULL)) AS 13,
       sum(IF(B.`ID`=14, B.`Rating`, NULL)) AS 14,
       sum(IF(B.`ID`=15, B.`Rating`, NULL)) AS 15,
       sum(IF(B.`ID`=16, B.`Rating`, NULL)) AS 16,
       sum(IF(B.`ID`=17, B.`Rating`, NULL)) AS 17,
       sum(IF(B.`ID`=18, B.`Rating`, NULL)) AS 18,
       sum(IF(B.`ID`=19, B.`Rating`, NULL)) AS 19,
       sum(IF(B.`ID`=20, B.`Rating`, NULL)) AS 20,
       sum(IF(B.`ID`=21, B.`Rating`, NULL)) AS 21,
       sum(IF(B.`ID`=22, B.`Rating`, NULL)) AS 22,
       sum(IF(B.`ID`=23, B.`Rating`, NULL)) AS 23,
       sum(IF(B.`ID`=24, B.`Rating`, NULL)) AS 24,
       sum(IF(B.`ID`=25, B.`Rating`, NULL)) AS 25,
       sum(IF(B.`ID`=26, B.`Rating`, NULL)) AS 26,
       sum(IF(B.`ID`=27, B.`Rating`, NULL)) AS 27,
       sum(IF(B.`ID`=28, B.`Rating`, NULL)) AS 28,
       sum(IF(B.`ID`=29, B.`Rating`, NULL)) AS 29,
       sum(IF(B.`ID`=30, B.`Rating`, NULL)) AS 30
FROM `BookRatings` AS B
GROUP BY B.`ISBN`;
